### ISSUE TITLE
Убрать бы жесткую привязку к бутстрапу

### ISSUE THREAD

**Issue by andrey-helldar** [garf/laravel-notifications#11]
Судя по описанию в ридми, пакет имеет жесткую привязку к бутстрапу.
А если юзать на сайте, где его нет? Например, в последнее время использую только MaterializeCSS...

**Comment by garf** [comment]
Здравствуйте.
Пакет не имеет жесткой привязки.
Он просто имеет готовую HTML-разметку для Bootstrap.
Если хотите сделать свою, вам нужно опубликовать ассеты пакета и изменить blade-файл появившийся в папке `resources/views/vendor/laravel-notifications`
Либо создать в этой папке свой view-файл и указать его в опубликованной конфигурации пакета.
